# Задача 1

In [2]:
import numpy as np
import scipy

In [9]:
a=np.random.random((10,3))
a[np.arange(10),np.absolute(a-0.5).argmin(axis=1)]

array([0.88675302, 0.37030069, 0.41045045, 0.34732322, 0.27129695,
       0.54367103, 0.5251199 , 0.5813173 , 0.42809932, 0.82623429])

# Задача 2 

In [10]:
a=np.random.random((6,6))
a.sum(axis=1)/a.min(axis=0)

array([125.62125199,  11.83580946,  24.10828781,  23.43872107,
        20.21362057,  15.87934243])

# Задача 3

In [11]:
a=np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask=a==0
a[1:][mask[:-1]].max()
print(a[1:][mask[:-1]].max())

5


# Задача 4

In [12]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
#g=[i==j for j in range (10)]
#g=np.array(g)
#a=g.sum(axis=1)
a=np.array([i==j for j in range (10)]).sum(axis=1)+x
print(a)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


# Задача 5

In [20]:
a=np.arange(16).reshape(4,4).reshape(1,16)
a=a[0]
n=7
m=4
c=[[a[i+(n//2)*k] for k in range(i+1)] for i in range(n//2+1)]
f=[[a[n+m*i+(n//2)*(k)] for k in range(m-2-i+1)] for i in range(m-1)]
f=np.array(f)
c=np.array(c)
b=np.hstack((c, f))
d=dict(enumerate(b))
d

{0: [0],
 1: [1, 4],
 2: [2, 5, 8],
 3: [3, 6, 9, 12],
 4: [7, 10, 13],
 5: [11, 14],
 6: [15]}

# Задача 6

In [2]:
import numpy as np 
from scipy.cluster.vq import kmeans
data = np.genfromtxt('geysers.csv', delimiter=',', skip_header=1)


In [3]:
data-=data.mean(axis=0)
data/=data.std(axis=0)


In [11]:
def kmeans1(data,k,it=20,thresh=1e-05): 
    n=data.shape[0]
    m=data.shape[1]
    centroids=data[:k]  
    data=np.expand_dims(data,axis=1) 
    i=0
    distortion=1e100
    distortion1=0
    while abs(distortion1-distortion) > thresh and i<it:
        distortion1=distortion
        centroids1=centroids
        arr=data-centroids
        labels=np.argmin((arr**2).sum(axis=2),axis=1) 
        a = np.zeros(n*m*k).reshape(n,k,m)
        a[np.arange(n),labels]=arr[np.arange(n),labels]/np.bincount(labels)[labels].reshape(n, 1)
        centroids=centroids1+a.sum(axis=0)
        arr=data-centroids
        labels=np.argmin((arr**2).sum(axis=2),axis=1)
        a=np.zeros(n*m*k).reshape(n,k,m)
        a[np.arange(n),labels]=arr[np.arange(n),labels]
        distortion=np.sqrt((a**2).sum(axis=2)).sum(axis=1).mean()         
        i=i+1
    return centroids,distortion
print(kmeans(data,3))
print(kmeans1(data,3))

(array([[-1.27243544, -1.20871494],
       [ 0.49401042,  0.32754064],
       [ 0.87916057,  0.95176708]]), 0.39879130260822226)
(array([[ 0.88086224,  0.89735086],
       [-1.27243544, -1.20871494],
       [ 0.42228532,  0.30345458]]), 0.3993167936672239)
